language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "jinahya-github"
    token: ${SONAR_TOKEN}
    branches:
      - master
      - develop

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  #- sonar-scanner